version: "3.7"

services:

  # ====================================================================================================================
  # POSTGRES SERVER
  # ====================================================================================================================
  pg-docker:
    image: postgres:14-alpine
    container_name: dev-postgresql
    restart: unless-stopped
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5433:5432
    volumes:
      - dev-postgres-data:/var/lib/postgresql/data
    networks:
      - dev-network

  # ====================================================================================================================
  # PGADMIN
  # ====================================================================================================================
  pgadmin-docker:
    image: dpage/pgadmin4
    container_name: dev-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@email.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    ports:
      - 6432:80
    volumes:
      - dev-pgadmin-data:/var/lib/pgadmin
    depends_on:
      - pg-docker
    networks:
      - dev-network

# ======================================================================================================================
# VOLUMES
# ======================================================================================================================
volumes:
    dev-postgres-data:
    dev-pgadmin-data:

# ======================================================================================================================
# REDE
# ======================================================================================================================
networks:
  dev-network:
    driver: bridge