server:
  port: 8081

spring:
  application:
    name: dscatalog

  profiles:
    active: ${APP_PROFILE:test}

  jpa:
    defer-datasource-initialization: false
    open-in-view: false
    hibernate:
      ddl-auto: none
    show-sql: false

  messages:
    basename: messages
    encoding: UTF-8
    fallback-to-system-locale: false

  mail:
    host: ${EMAIL_HOST:smtp.gmail.com}
    port: ${EMAIL_PORT:587}
    username: ${EMAIL_USERNAME:test@gmail.com}
    password: ${EMAIL_PASSWORD:123456}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
      sender:
        timeout: 60

email:
  password-recovery:
    token:
      minutes: ${PASSWORD_RECOVERY_TOKEN_MINUTES:30}
    uri: ${PASSWORD_RECOVERY_URI:http://localhost:5173/password/recovery}

security:
  client-id: ${CLIENT_ID:dscatalog}
  client-secret: ${CLIENT_SECRET:123456}
  jwt:
    duration: ${JWT_DURATION:86400}

cors:
  origins: ${CORS_ORIGINS:http://localhost:3000,http://localhost:5173}

logging:
  level:
    root: info
    org.springframework.web: error
    org.hibernate: error
    org.springframework.security: error
